In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
public_school=pd.read_csv('../data/Public_School_Characteristics_2022-23 (1).csv')

C:\Users\Mahboba\AppData\Local\Temp\ipykernel_50444\1745329213.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  public_school=pd.read_csv('../data/Public_School_Characteristics_2022-23 (1).csv')

In [3]:
public_school

,X,Y,OBJECTID,NCESSCH,SURVYEAR,STABR,LEAID,ST_LEAID,LEA_NAME,SCH_NAME,...,HIALF,HI,TRALM,TRALF,TR,WHALM,WHALF,WH,LATCOD,LONCOD
0,-86.206200,34.260200,1,10000500870,2022-2023,AL,100005,AL-101,Albertville City,Albertville Middle School,...,251.0,502.0,17.0,15.0,32.0,168.0,147.0,315.0,34.260200,-86.206200
1,-86.204900,34.262200,2,10000500871,2022-2023,AL,100005,AL-101,Albertville City,Albertville High School,...,468.0,958.0,26.0,19.0,45.0,325.0,316.0,641.0,34.262200,-86.204900
2,-86.220100,34.273300,3,10000500879,2022-2023,AL,100005,AL-101,Albertville City,Albertville Intermediate School,...,241.0,504.0,7.0,6.0,13.0,154.0,144.0,298.0,34.273300,-86.220100
3,-86.221806,34.252700,4,10000500889,2022-2023,AL,100005,AL-101,Albertville City,Albertville Elementary School,...,236.0,497.0,11.0,16.0,27.0,168.0,136.0,304.0,34.252700,-86.221806
4,-86.193300,34.289800,5,10000501616,2022-2023,AL,100005,AL-101,Albertville City,Albertville Kindergarten and PreK,...,152.0,319.0,4.0,4.0,8.0,104.0,120.0,224.0,34.289800,-86.193300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101385,-64.917602,18.341950,101386,780003000024,2022-2023,VI,7800030,VI-001,Saint Thomas - Saint John School District,LOCKHART ELEMENTARY SCHOOL,...,30.0,63.0,1.0,2.0,3.0,1.0,0.0,1.0,18.341950,-64.917602
101386,-64.952483,18.338742,101387,780003000026,2022-2023,VI,7800030,VI-001,Saint Thomas - Saint John School District,ULLA F MULLER ELEMENTARY SCHOOL,...,27.0,54.0,2.0,0.0,2.0,2.0,5.0,7.0,18.338742,-64.952483
101387,-64.899024,18.354782,101388,780003000027,2022-2023,VI,7800030,VI-001,Saint Thomas - Saint John School District,YVONNE BOWSKY ELEMENTARY SCHOOL,...,22.0,59.0,0.0,1.0,1.0,8.0,4.0,12.0,18.354782,-64.899024
101388,-64.945940,18.336658,101389,780003000033,2022-2023,VI,7800030,VI-001,Saint Thomas - Saint John School District,CANCRYN JUNIOR HIGH SCHOOL,...,62.0,136.0,0.0,1.0,1.0,6.0,10.0,16.0,18.336658,-64.945940
101389,-64.890311,18.318230,101390,780003000034,2022-2023,VI,7800030,VI-001,Saint Thomas - Saint John School District,BERTHA BOSCHULTE JUNIOR HIGH,...,21.0,48.0,0.0,0.0,0.0,0.0,2.0,2.0,18.318230,-64.890311

In [4]:
public_school = public_school.drop(columns=['X', 'Y'])

In [5]:
public_school

,OBJECTID,NCESSCH,SURVYEAR,STABR,LEAID,ST_LEAID,LEA_NAME,SCH_NAME,LSTREET1,LSTREET2,...,HIALF,HI,TRALM,TRALF,TR,WHALM,WHALF,WH,LATCOD,LONCOD
0,1,10000500870,2022-2023,AL,100005,AL-101,Albertville City,Albertville Middle School,600 E Alabama Ave,NaN,...,251.0,502.0,17.0,15.0,32.0,168.0,147.0,315.0,34.260200,-86.206200
1,2,10000500871,2022-2023,AL,100005,AL-101,Albertville City,Albertville High School,402 E McCord Ave,NaN,...,468.0,958.0,26.0,19.0,45.0,325.0,316.0,641.0,34.262200,-86.204900
2,3,10000500879,2022-2023,AL,100005,AL-101,Albertville City,Albertville Intermediate School,901 W McKinney Ave,NaN,...,241.0,504.0,7.0,6.0,13.0,154.0,144.0,298.0,34.273300,-86.220100
3,4,10000500889,2022-2023,AL,100005,AL-101,Albertville City,Albertville Elementary School,145 West End Drive,NaN,...,236.0,497.0,11.0,16.0,27.0,168.0,136.0,304.0,34.252700,-86.221806
4,5,10000501616,2022-2023,AL,100005,AL-101,Albertville City,Albertville Kindergarten and PreK,257 Country Club Rd,NaN,...,152.0,319.0,4.0,4.0,8.0,104.0,120.0,224.0,34.289800,-86.193300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101385,101386,780003000024,2022-2023,VI,7800030,VI-001,Saint Thomas - Saint John School District,LOCKHART ELEMENTARY SCHOOL,41 ESTATE THOMAS,NaN,...,30.0,63.0,1.0,2.0,3.0,1.0,0.0,1.0,18.341950,-64.917602
101386,101387,780003000026,2022-2023,VI,7800030,VI-001,Saint Thomas - Saint John School District,ULLA F MULLER ELEMENTARY SCHOOL,7B ESTATE CONTANT,NaN,...,27.0,54.0,2.0,0.0,2.0,2.0,5.0,7.0,18.338742,-64.952483
101387,101388,780003000027,2022-2023,VI,7800030,VI-001,Saint Thomas - Saint John School District,YVONNE BOWSKY ELEMENTARY SCHOOL,15B and 16 ESTATE MANDAHL,NaN,...,22.0,59.0,0.0,1.0,1.0,8.0,4.0,12.0,18.354782,-64.899024
101388,101389,780003000033,2022-2023,VI,7800030,VI-001,Saint Thomas - Saint John School District,CANCRYN JUNIOR HIGH SCHOOL,1 CROWN BAY,NaN,...,62.0,136.0,0.0,1.0,1.0,6.0,10.0,16.0,18.336658,-64.945940
101389,101390,780003000034,2022-2023,VI,7800030,VI-001,Saint Thomas - Saint John School District,BERTHA BOSCHULTE JUNIOR HIGH,9 1 and 12A BOVONI,NaN,...,21.0,48.0,0.0,0.0,0.0,0.0,2.0,2.0,18.318230,-64.890311

In [6]:
public_school.rename(columns={'STABR': 'STATE', 'LEA_NAME':'COUNTY', 'STUTERATIO': 'STUDENT-TEACHER-RATIO','LATCOD':'LAT',
                              'LONCOD':'LON'                           
}, inplace=True)

In [7]:
public_school

,OBJECTID,NCESSCH,SURVYEAR,STATE,LEAID,ST_LEAID,COUNTY,SCH_NAME,LSTREET1,LSTREET2,...,HIALF,HI,TRALM,TRALF,TR,WHALM,WHALF,WH,LAT,LON
0,1,10000500870,2022-2023,AL,100005,AL-101,Albertville City,Albertville Middle School,600 E Alabama Ave,NaN,...,251.0,502.0,17.0,15.0,32.0,168.0,147.0,315.0,34.260200,-86.206200
1,2,10000500871,2022-2023,AL,100005,AL-101,Albertville City,Albertville High School,402 E McCord Ave,NaN,...,468.0,958.0,26.0,19.0,45.0,325.0,316.0,641.0,34.262200,-86.204900
2,3,10000500879,2022-2023,AL,100005,AL-101,Albertville City,Albertville Intermediate School,901 W McKinney Ave,NaN,...,241.0,504.0,7.0,6.0,13.0,154.0,144.0,298.0,34.273300,-86.220100
3,4,10000500889,2022-2023,AL,100005,AL-101,Albertville City,Albertville Elementary School,145 West End Drive,NaN,...,236.0,497.0,11.0,16.0,27.0,168.0,136.0,304.0,34.252700,-86.221806
4,5,10000501616,2022-2023,AL,100005,AL-101,Albertville City,Albertville Kindergarten and PreK,257 Country Club Rd,NaN,...,152.0,319.0,4.0,4.0,8.0,104.0,120.0,224.0,34.289800,-86.193300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101385,101386,780003000024,2022-2023,VI,7800030,VI-001,Saint Thomas - Saint John School District,LOCKHART ELEMENTARY SCHOOL,41 ESTATE THOMAS,NaN,...,30.0,63.0,1.0,2.0,3.0,1.0,0.0,1.0,18.341950,-64.917602
101386,101387,780003000026,2022-2023,VI,7800030,VI-001,Saint Thomas - Saint John School District,ULLA F MULLER ELEMENTARY SCHOOL,7B ESTATE CONTANT,NaN,...,27.0,54.0,2.0,0.0,2.0,2.0,5.0,7.0,18.338742,-64.952483
101387,101388,780003000027,2022-2023,VI,7800030,VI-001,Saint Thomas - Saint John School District,YVONNE BOWSKY ELEMENTARY SCHOOL,15B and 16 ESTATE MANDAHL,NaN,...,22.0,59.0,0.0,1.0,1.0,8.0,4.0,12.0,18.354782,-64.899024
101388,101389,780003000033,2022-2023,VI,7800030,VI-001,Saint Thomas - Saint John School District,CANCRYN JUNIOR HIGH SCHOOL,1 CROWN BAY,NaN,...,62.0,136.0,0.0,1.0,1.0,6.0,10.0,16.0,18.336658,-64.945940
101389,101390,780003000034,2022-2023,VI,7800030,VI-001,Saint Thomas - Saint John School District,BERTHA BOSCHULTE JUNIOR HIGH,9 1 and 12A BOVONI,NaN,...,21.0,48.0,0.0,0.0,0.0,0.0,2.0,2.0,18.318230,-64.890311

In [8]:
average_ratio = public_school.groupby('STATE')['STUDENT-TEACHER-RATIO'].mean().sort_values(ascending=False)

In [9]:
average_ratio

STATE
UT    22.227065
ID    21.913993
MP    20.646286
CA    20.448313
AK    20.003327
NV    19.306946
LA    18.752526
OR    18.435000
WA    18.321283
MI    17.944259
FL    17.821031
OH    17.812229
NC    17.095479
CO    16.694820
IN    15.851567
OK    15.771317
AL    15.512184
WI    15.153652
ND    15.146170
KY    15.095163
TN    14.990611
NM    14.704739
IA    14.516768
HI    14.234915
GA    14.207708
MD    13.906375
MN    13.562172
KS    13.511733
SC    13.445494
SD    13.411092
AR    13.353365
PA    13.256630
TX    13.201506
DE    13.184807
NE    13.161249
IL    12.855543
RI    12.802405
WV    12.556204
MA    11.997383
VT    11.978977
VI    11.855000
MO    11.735956
CT    11.674149
DC    11.620370
VA    11.501384
NY    11.491423
NJ    11.445600
WY    11.400583
MS    11.373229
MT    11.275935
NH    11.156420
ME    10.293099
PR    10.096410
AZ     9.450440
GU    -1.000000
AS    -1.000000
Name: STUDENT-TEACHER-RATIO, dtype: float64

In [10]:
import folium

In [11]:
county_lat_lon = public_school.groupby(['STATE', 'COUNTY'])[['LAT', 'LON']].mean().reset_index()

In [12]:
county_state_avg_ratio = public_school.groupby(['STATE', 'COUNTY'])['STUDENT-TEACHER-RATIO'].mean().reset_index()

In [13]:
county_state_avg_ratio

,STATE,COUNTY,STUDENT-TEACHER-RATIO
0,AK,Alaska Gateway School District,13.076250
1,AK,Aleutian Region School District,4.000000
2,AK,Aleutians East Borough School District,8.727500
3,AK,Anchorage School District,18.386701
4,AK,Annette Island School District,9.490000
...,...,...,...
18422,WY,Weston County School District #1,11.205000
18423,WY,Weston County School District #7,32.960000
18424,WY,Wyoming Behavioral Institute - Administration ...,NaN
18425,WY,Wyoming Department of Family Services,NaN
18426,WY,Youth Emergency Services Inc. - Administration...,NaN

In [14]:
state_lat_lon = public_school.groupby('STATE')[['LAT', 'LON']].mean().reset_index()

In [15]:
state_lat_lon

   STATE        LAT         LON
0     AK  61.248867 -150.627365
1     AL  33.043952  -86.731934
2     AR  35.142685  -92.663272
3     AS -14.285068 -170.531904
4     AZ  33.429240 -111.746368
5     CA  35.827398 -119.589642
6     CO  39.414667 -105.202297
7     CT  41.513322  -72.851081
8     DC  38.903869  -76.997260
9     DE  39.318895  -75.557814
10    FL  27.976769  -81.788721
11    GA  33.315364  -83.872996
12    GU  13.465629  144.787329
13    HI  21.053449 -157.405241
14    IA  41.981187  -93.183392
15    ID  44.132187 -114.940072
16    IL  41.054152  -88.546773
17    IN  40.112714  -86.251820
18    KS  38.417820  -96.910441
19    KY  37.752319  -85.181508
20    LA  30.790220  -91.640000
21    MA  42.277899  -71.439415
22    MD  39.138252  -76.811977
23    ME  44.448081  -69.513836
24    MI  42.939060  -84.375732
25    MN  45.238934  -93.702011
26    MO  38.404588  -92.388648
27    MP  15.064729  145.678712
28    MS  32.650927  -89.597234
29    MT  46.975372 -110.415220
30    NC  35.562802  -79.652193
31    ND  47.398223  -99.789638
32    NE  41.247717  -97.866288
33    NH  43.256249  -71.530786
34    NJ  40.439883  -74.454990
35    NM  34.668140 -106.257375
36    NV  37.507032 -116.435690
37    NY  41.617017  -74.740188
38    OH  40.460761  -82.757441
39    OK  35.535741  -96.910614
40    OR  44.619209 -122.316095
41    PA  40.482275  -77.181642
42    PR  18.260897  -66.358830
43    RI  41.761511  -71.455126
44    SC  34.036804  -81.018348
45    SD  44.170984  -98.881206
46    TN  35.817166  -86.389936
47    TX  30.961296  -97.523521
48    UT  40.250234 -111.913384
49    VA  37.754650  -78.027761
50    VI  18.034196  -64.839921
51    VT  44.055517  -72.752088
52    WA  47.295003 -121.363009
53    WI  43.861228  -89.253673
54    WV  38.737375  -80.769745
55    WY  42.806142 -107.114022

In [16]:
average_state_ratio = average_ratio_state.merge(state_lat_lon, on='STATE', how='left')

In [17]:
county_state_avg_ratio

,STATE,COUNTY,STUDENT-TEACHER-RATIO,LAT,LON
0,AK,Alaska Gateway School District,13.076250,61.248867,-150.627365
1,AK,Aleutian Region School District,4.000000,61.248867,-150.627365
2,AK,Aleutians East Borough School District,8.727500,61.248867,-150.627365
3,AK,Anchorage School District,18.386701,61.248867,-150.627365
4,AK,Annette Island School District,9.490000,61.248867,-150.627365
...,...,...,...,...,...
18422,WY,Weston County School District #1,11.205000,42.806142,-107.114022
18423,WY,Weston County School District #7,32.960000,42.806142,-107.114022
18424,WY,Wyoming Behavioral Institute - Administration ...,NaN,42.806142,-107.114022
18425,WY,Wyoming Department of Family Services,NaN,42.806142,-107.114022
18426,WY,Youth Emergency Services Inc. - Administration...,NaN,42.806142,-107.114022

In [18]:
state_avg_ratio = county_state_avg_ratio .drop(columns=['LAT_x', 'LON_x'])

KeyError: "['LAT_x', 'LON_x'] not found in axis"

In [ ]:
state_avg_ratio.rename(columns={'LAT_y': 'LAT', 'LON_y': 'LON'}, inplace=True)

In [ ]:
m = folium.Map(location=[37.0902, -95.7129], zoom_start=5)  # U.S. center coordinates

for _, row in average_ratio.iterrows():
    state = row['STATE']
    average_ratio= row['STUDENT-TEACHER-RATIO']
    
    lat = row['LAT']
    lon = row['LON']
    
    folium.CircleMarker(
        location=[lat, lon],
        radius=7,  
        color='light green',  
        fill=True,
        fill_color='light green',  
        fill_opacity=0.6,
        popup=f"{state}: {avg_ratio:.2f} student-teacher ratio"  
    ).add_to(m)

m.save("state_student_teacher_ratio_map.html")
m